<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "transfer_mietwagen"
 *
 * Auto generated by Extension Builder 2020-05-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Transfer und Mietwagen',
    'description' => 'Transfer und Mietwagen. Buchung und Verwaltung.',
    'category' => 'plugin',
    'author' => 'Stolberg',
    'author_email' => 'p.stolberg@gmx.de',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
